# Configuration
CODEX_PM_INSTALL_DIR="$HOME/.local/share/codex-profile-manager"
CODEX_PM_STATE_DIR="$CODEX_PM_INSTALL_DIR"
CODEX_PM_ACCOUNTS_DIR="$CODEX_PM_STATE_DIR/accounts"
CODEX_PM_PROJECTS_DIR="$CODEX_PM_STATE_DIR/projects"
CODEX_PM_DEFAULT_ACCOUNT_FILE="$CODEX_PM_STATE_DIR/default-account"
CODEX_PM_CURRENT_ACCOUNT="${CODEX_PM_CURRENT_ACCOUNT:-}"
